title: Satyam Mittal
email: satyam101905@gmail.com
description: "This is my profile where I present Satyam Mittal to the world."
baseurl: ""
url: "https://05satyam.github.io"
linkedin_username: satyam-sm
github_username: 05satyam
theme: minima
resumename: Resume-Satyam.pdf
